apiVersion: pipecd.dev/v1beta1
kind: Application
spec:
  name: simple-app
  plugin: ecs
  deployTarget: ecs-dev
  labels:
    env: demo
    plugin: ecs
  plugins:
    ecs:
      input:
        serviceDefinitionFile: servicedef.yaml
        taskDefinitionFile: taskdef.yaml
        clusterArn: arn:aws:ecs:us-east-1:992382718026:cluster/pipecd-ecs-test-cluster
        awsvpcConfiguration:
          assignPublicIp: ENABLED
          subnets:
            - subnet-06ad2d6513d48f198
          securityGroups:
            - sg-0a17a054155fe56de
        runStandaloneTask: true
        accessType: SERVICE_DISCOVERY
      quickSync:
        recreate: true
  planner:
    autoRollback: false
  pipeline:
    rollback: false
    stages:
      - name: ECS_CANARY_CLEAN
  description: |
    Simple ECS Plugin Demo Application

